# ==============================================================================
# KRIYA Local Database: Conversation Queries (SQLite)
# ==============================================================================
# Self-contained SQLite implementation of conversation persistence.
# Keeps identical function signatures to ensure complete zero-breaking compatibility
# with FastAPI endpoints and agent loops.
# ==============================================================================

import json
import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from agent.database.sqlite_db import (
    execute_query,
    fetch_one,
    fetch_all,
    init_sqlite_db,
)


class ChatMessageRecord(BaseModel):
    role: str = Field(..., description="Role: 'user', 'assistant', 'system', or 'tool'")
    content: str = Field(default="", description="Text message content or final response")
    tool_calls: Optional[List[Dict[str, Any]]] = Field(default=None, description="Tool calls generated by assistant")
    timestamp: Optional[str] = Field(default=None, description="ISO timestamp of message creation")


class ConversationRecord(BaseModel):
    id: str = Field(..., description="Unique conversation identifier")
    name: str = Field(default="", description="Conversation title (2-3 words)")
    employee_id: Optional[str] = Field(default=None, description="Associated employee account")
    messages: List[Dict[str, Any]] = Field(default_factory=list, description="Array of message exchanges")
    created_at: Optional[str] = None
    updated_at: Optional[str] = None


class ConversationListItem(BaseModel):
    id: str = Field(..., description="Unique conversation identifier")
    name: str = Field(default="New Chat", description="Conversation title for the chats panel")


async def create_conversation(
    custom_id: Optional[str] = None,
    employee_id: Optional[str] = None
) -> Dict[str, Any]:
    """
    Creates a new conversation record in local SQLite.
    """
    await init_sqlite_db()
    conv_id = custom_id or str(uuid.uuid4())[:8]
    now_iso = datetime.utcnow().isoformat()
    empty_messages_json = json.dumps([])

    sql = """
    INSERT INTO conversations (id, name, employee_id, messages, created_at, updated_at)
    VALUES (?, ?, ?, ?, ?, ?)
    ON CONFLICT(id) DO UPDATE SET
        employee_id = COALESCE(conversations.employee_id, excluded.employee_id),
        updated_at = excluded.updated_at
    """
    await execute_query(sql, (conv_id, "New Chat", employee_id, empty_messages_json, now_iso, now_iso))

    return {
        "id": conv_id,
        "name": "New Chat",
        "employee_id": employee_id,
        "messages": [],
        "created_at": now_iso,
        "updated_at": now_iso
    }


async def get_conversation(
    conv_id: str,
    employee_id: Optional[str] = None
) -> Optional[Dict[str, Any]]:
    """
    Retrieves a conversation and its messages history from local SQLite.
    If employee_id is provided, scopes the search to that user.
    """
    await init_sqlite_db()
    if employee_id:
        sql = """
        SELECT id, name, employee_id, messages, created_at, updated_at
        FROM conversations
        WHERE id = ? AND employee_id = ?
        """
        row = await fetch_one(sql, (conv_id, employee_id))
    else:
        sql = """
        SELECT id, name, employee_id, messages, created_at, updated_at
        FROM conversations
        WHERE id = ?
        """
        row = await fetch_one(sql, (conv_id,))

    if not row:
        return None

    raw_msgs = row.get("messages", "[]")
    if isinstance(raw_msgs, str):
        try:
            messages_list = json.loads(raw_msgs)
        except Exception:
            messages_list = []
    elif isinstance(raw_msgs, list):
        messages_list = raw_msgs
    else:
        messages_list = []

    return {
        "id": row["id"],
        "name": row["name"] or "New Chat",
        "employee_id": row["employee_id"],
        "messages": messages_list,
        "created_at": str(row["created_at"]) if row.get("created_at") else None,
        "updated_at": str(row["updated_at"]) if row.get("updated_at") else None,
    }


async def list_conversations(
    employee_id: Optional[str] = None,
    limit: int = 50
) -> List[Dict[str, Any]]:
    """
    Returns list of conversations for the frontend chats panel from local SQLite.
    """
    await init_sqlite_db()
    if employee_id:
        sql = """
        SELECT id, name
        FROM conversations
        WHERE employee_id = ?
        ORDER BY updated_at DESC
        LIMIT ?
        """
        rows = await fetch_all(sql, (employee_id, limit))
    else:
        sql = """
        SELECT id, name
        FROM conversations
        ORDER BY updated_at DESC
        LIMIT ?
        """
        rows = await fetch_all(sql, (limit,))

    return [
        {
            "id": r["id"],
            "name": r["name"] if r.get("name") else "New Chat"
        }
        for r in rows
    ]


async def append_messages_to_conversation(
    conv_id: str,
    new_messages: List[Dict[str, Any]],
    employee_id: Optional[str] = None
) -> bool:
    """
    Appends new user/assistant message exchanges to the conversation in local SQLite.
    """
    await init_sqlite_db()
    row = await fetch_one("SELECT messages FROM conversations WHERE id = ?", (conv_id,))
    if row and row.get("messages"):
        raw_existing = row["messages"]
        if isinstance(raw_existing, str):
            try:
                current_list = json.loads(raw_existing)
            except Exception:
                current_list = []
        elif isinstance(raw_existing, list):
            current_list = raw_existing
        else:
            current_list = []
    else:
        current_list = []

    current_list.extend(new_messages)
    updated_json = json.dumps(current_list)
    now_iso = datetime.utcnow().isoformat()

    sql = """
    INSERT INTO conversations (id, name, employee_id, messages, created_at, updated_at)
    VALUES (?, 'New Chat', ?, ?, ?, ?)
    ON CONFLICT(id) DO UPDATE SET
        messages = excluded.messages,
        employee_id = COALESCE(conversations.employee_id, excluded.employee_id),
        updated_at = excluded.updated_at
    """
    rowcount = await execute_query(sql, (conv_id, employee_id, updated_json, now_iso, now_iso))
    return rowcount > 0


async def update_conversation_name(conv_id: str, new_name: str) -> bool:
    """
    Sets the title / name of the conversation in local SQLite.
    """
    await init_sqlite_db()
    now_iso = datetime.utcnow().isoformat()
    sql = """
    UPDATE conversations
    SET name = ?, updated_at = ?
    WHERE id = ?
    """
    rowcount = await execute_query(sql, (new_name.strip(), now_iso, conv_id))
    return rowcount > 0


async def delete_conversation(conv_id: str) -> bool:
    """
    Deletes a conversation record from local SQLite.
    """
    await init_sqlite_db()
    sql = "DELETE FROM conversations WHERE id = ?"
    rowcount = await execute_query(sql, (conv_id,))
    return rowcount > 0
