# ==============================================================================
# KRIYA Database Schema: Conversations & Chats
# ==============================================================================
# Defines the PostgreSQL table schema and Pydantic models for storing chat
# conversations, including user prompts, AI reasoning, tool calls, and responses.
# ==============================================================================

from typing import Any, Dict, List, Optional
from datetime import datetime
from pydantic import BaseModel, Field


# 1. SQL DDL to initialize the conversations table in PostgreSQL
CREATE_CONVERSATIONS_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS conversations (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL DEFAULT '',
    messages JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_conversations_updated_at ON conversations (updated_at DESC);
"""


# 2. Pydantic Model for an individual message item inside the JSON exchange
class ChatMessageRecord(BaseModel):
    role: str = Field(..., description="Role: 'user', 'assistant', 'system', or 'tool'")
    content: str = Field(default="", description="Text message content or final response")
    tool_calls: Optional[List[Dict[str, Any]]] = Field(default=None, description="Tool calls generated by assistant")
    timestamp: Optional[str] = Field(default=None, description="ISO timestamp of message creation")


# 3. Pydantic Model representing a full Conversation record from the database
class ConversationRecord(BaseModel):
    id: str = Field(..., description="Unique conversation identifier (UUID or short hash)")
    name: str = Field(default="", description="Conversation title (2-3 words generated by mini-agent)")
    messages: List[Dict[str, Any]] = Field(default_factory=list, description="Array of message exchanges in OpenAI JSON format")
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


# 4. Pydantic Model for listing conversations in the chats panel (ID and name only)
class ConversationListItem(BaseModel):
    id: str = Field(..., description="Unique conversation identifier")
    name: str = Field(default="New Chat", description="Conversation title for the chats panel")

