# ==============================================================================
# KRIYA Database Request Logic: Conversation Queries
# ==============================================================================
# Contains asyncpg database query functions for managing conversations:
# - init_db: Creates tables if not exist
# - create_conversation: Starts a new empty conversation with ID
# - get_conversation: Loads chat history from PostgreSQL
# - list_conversations: Lists chats for the sidebar
# - append_messages_to_conversation: Appends user + assistant exchange
# - update_conversation_name: Sets the 2-3 word title generated by mini-agent
# - delete_conversation: Removes a conversation
# ==============================================================================

import json
import os
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional
import asyncpg
from dotenv import load_dotenv

from backend.database.kriya_db.schema.conversation import CREATE_CONVERSATIONS_TABLE_SQL

# Load DATABASE_URL from .env
env_path = Path(__file__).resolve().parent.parent.parent.parent.parent / ".env"
load_dotenv(dotenv_path=env_path)

DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://postgres@localhost:5432/kriya_db")

_pool: Optional[asyncpg.Pool] = None


async def get_db_pool() -> asyncpg.Pool:
    """Returns or creates the global asyncpg connection pool."""
    global _pool
    if _pool is None:
        _pool = await asyncpg.create_pool(DATABASE_URL, min_size=1, max_size=10)
        # Ensure table exists on first connection
        async with _pool.acquire() as conn:
            await conn.execute(CREATE_CONVERSATIONS_TABLE_SQL)
    return _pool


async def create_conversation(custom_id: Optional[str] = None) -> Dict[str, Any]:
    """
    Creates a new conversation record in PostgreSQL with an empty title and empty messages list.
    """
    pool = await get_db_pool()
    conv_id = custom_id or str(uuid.uuid4())[:8]
    empty_messages_json = json.dumps([])

    async with pool.acquire() as conn:
        await conn.execute(
            """
            INSERT INTO conversations (id, name, messages, created_at, updated_at)
            VALUES ($1, $2, $3::jsonb, NOW(), NOW())
            ON CONFLICT (id) DO NOTHING
            """,
            conv_id, "", empty_messages_json
        )

    return {
        "id": conv_id,
        "name": "New Chat",
        "messages": [],
        "created_at": datetime.utcnow().isoformat(),
        "updated_at": datetime.utcnow().isoformat()
    }


async def get_conversation(conv_id: str) -> Optional[Dict[str, Any]]:
    """
    Retrieves a conversation and its full JSON messages history from PostgreSQL.
    """
    pool = await get_db_pool()
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            """
            SELECT id, name, messages, created_at, updated_at
            FROM conversations
            WHERE id = $1
            """,
            conv_id
        )

    if not row:
        return None

    # Parse messages JSONB
    messages_data = row["messages"]
    if isinstance(messages_data, str):
        try:
            messages_list = json.loads(messages_data)
        except Exception:
            messages_list = []
    elif isinstance(messages_data, list):
        messages_list = messages_data
    else:
        messages_list = []

    return {
        "id": row["id"],
        "name": row["name"] or "New Chat",
        "messages": messages_list,
        "created_at": row["created_at"].isoformat() if row["created_at"] else None,
        "updated_at": row["updated_at"].isoformat() if row["updated_at"] else None
    }


async def list_conversations(limit: int = 50) -> List[Dict[str, Any]]:
    """
    Returns a list of conversations for the frontend chats panel containing
    only the conversation ID and name (content is queried only on click).
    """
    pool = await get_db_pool()
    async with pool.acquire() as conn:
        rows = await conn.fetch(
            """
            SELECT id, name
            FROM conversations
            ORDER BY updated_at DESC
            LIMIT $1
            """,
            limit
        )

    return [
        {
            "id": r["id"],
            "name": r["name"] if r["name"] else "New Chat"
        }
        for r in rows
    ]


async def append_messages_to_conversation(conv_id: str, new_messages: List[Dict[str, Any]]) -> bool:
    """
    Appends new user/assistant message exchanges to the conversation's messages array in PostgreSQL.
    """
    pool = await get_db_pool()
    async with pool.acquire() as conn:
        # Fetch existing messages
        existing = await conn.fetchval(
            "SELECT messages FROM conversations WHERE id = $1",
            conv_id
        )

        if existing is None:
            # If conversation does not exist, create it first
            current_list = []
        elif isinstance(existing, str):
            try:
                current_list = json.loads(existing)
            except Exception:
                current_list = []
        elif isinstance(existing, list):
            current_list = existing
        else:
            current_list = []

        # Append new messages
        current_list.extend(new_messages)
        updated_json = json.dumps(current_list)

        # Update in database
        result = await conn.execute(
            """
            INSERT INTO conversations (id, name, messages, updated_at)
            VALUES ($1, '', $2::jsonb, NOW())
            ON CONFLICT (id) DO UPDATE
            SET messages = $2::jsonb, updated_at = NOW()
            """,
            conv_id, updated_json
        )
        return "UPDATE" in result or "INSERT" in result


async def update_conversation_name(conv_id: str, new_name: str) -> bool:
    """
    Sets the title / name of the conversation in PostgreSQL (e.g. generated by mini-agent).
    """
    pool = await get_db_pool()
    async with pool.acquire() as conn:
        result = await conn.execute(
            """
            UPDATE conversations
            SET name = $1, updated_at = NOW()
            WHERE id = $2
            """,
            new_name.strip(), conv_id
        )
        return "UPDATE 1" in result


async def delete_conversation(conv_id: str) -> bool:
    """
    Deletes a conversation record from PostgreSQL.
    """
    pool = await get_db_pool()
    async with pool.acquire() as conn:
        result = await conn.execute(
            "DELETE FROM conversations WHERE id = $1",
            conv_id
        )
        return "DELETE 1" in result
