from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    """Represents an individual message in a chat history."""
    role: str = Field(..., description="Role of the sender: system, user, assistant, or tool")
    content: Optional[str] = Field(None, description="Text content of the message")
    name: Optional[str] = Field(None, description="Optional name of the tool or agent")
    tool_call_id: Optional[str] = Field(None, description="Tool call reference ID if role is tool")
    tool_calls: Optional[List[Dict[str, Any]]] = Field(None, description="Tool calls generated by assistant")


class FunctionDefinition(BaseModel):
    """Defines a callable function schema for tool calling."""
    name: str = Field(..., description="Name of the function")
    description: Optional[str] = Field(None, description="Description of what the function does")
    parameters: Optional[Dict[str, Any]] = Field(None, description="JSON schema of function parameters")


class ToolDefinition(BaseModel):
    """OpenAI-compatible tool definition wrapper."""
    type: str = Field(default="function", description="Tool type, typically 'function'")
    function: FunctionDefinition = Field(..., description="Function specification")


class ModelRequest(BaseModel):
    """
    Complete business logic schema for sending generation requests
    to the Sovereign Load Balancer (:8000/v1).
    All fields are optional except for user_content.
    """
    user_content: str = Field(
        ...,
        description="The prompt or query from the user (Required)"
    )
    system_content: Optional[str] = Field(
        None,
        description="System instruction or persona for the model"
    )
    history_messages: Optional[List[ChatMessage]] = Field(
        default=None,
        description="Prior conversation history messages"
    )
    model: Optional[str] = Field(
        default="default",
        description="Target model or routing tag: 'default', 'general', 'coder', 'vision', etc."
    )
    temperature: Optional[float] = Field(
        default=0.2,
        description="Sampling temperature between 0.0 and 2.0"
    )
    top_p: Optional[float] = Field(
        default=0.95,
        description="Nucleus sampling threshold"
    )
    max_tokens: Optional[int] = Field(
        default=None,
        description="Maximum number of tokens to generate in the response"
    )
    stream: Optional[bool] = Field(
        default=False,
        description="Whether to stream back partial tokens as server-sent events"
    )
    tools: Optional[List[ToolDefinition]] = Field(
        default=None,
        description="List of available tools/functions the model may call"
    )
    tool_choice: Optional[Union[str, Dict[str, Any]]] = Field(
        default=None,
        description="Controls which tool is called: 'auto', 'none', 'required', or a specific function"
    )
    stop: Optional[Union[str, List[str]]] = Field(
        default=None,
        description="Sequences where the model will stop generating further tokens"
    )
    presence_penalty: Optional[float] = Field(
        default=None,
        description="Penalty for new tokens based on whether they appear in text so far"
    )
    frequency_penalty: Optional[float] = Field(
        default=None,
        description="Penalty for new tokens based on their frequency in text so far"
    )
    thinking: Optional[bool] = Field(
        default=None,
        description="Toggle reasoning/thinking mode for models supporting chain-of-thought (e.g., Qwen-Thinking, DeepSeek-R1)"
    )

    def to_messages_list(self) -> List[Dict[str, Any]]:
        """
        Converts system_content, history_messages, and user_content
        into a standard OpenAI message payload array.
        """
        messages: List[Dict[str, Any]] = []

        # 1. Add system prompt if present
        if self.system_content:
            messages.append({"role": "system", "content": self.system_content})

        # 2. Add conversation history if present
        if self.history_messages:
            for msg in self.history_messages:
                msg_dict = msg.model_dump(exclude_none=True)
                messages.append(msg_dict)

        # 3. Add latest user query
        messages.append({"role": "user", "content": self.user_content})
        return messages

    def to_openai_payload(self) -> Dict[str, Any]:
        """
        Converts the entire request into kwargs dictionary ready for client.chat.completions.create
        """
        payload: Dict[str, Any] = {
            "model": self.model or "default",
            "messages": self.to_messages_list(),
            "temperature": self.temperature if self.temperature is not None else 0.2,
            "stream": bool(self.stream),
        }

        if self.top_p is not None:
            payload["top_p"] = self.top_p
        if self.max_tokens is not None:
            payload["max_tokens"] = self.max_tokens
        if self.stop is not None:
            payload["stop"] = self.stop
        if self.presence_penalty is not None:
            payload["presence_penalty"] = self.presence_penalty
        if self.frequency_penalty is not None:
            payload["frequency_penalty"] = self.frequency_penalty

        if self.tools:
            payload["tools"] = [t.model_dump(exclude_none=True) for t in self.tools]
            if self.tool_choice:
                payload["tool_choice"] = self.tool_choice

        if self.thinking is not None:
            extra_body = payload.get("extra_body", {})
            extra_body["enable_thinking"] = self.thinking
            extra_body["chat_template_kwargs"] = {"enable_thinking": self.thinking}
            payload["extra_body"] = extra_body

        return payload
