# ==============================================================================
# KRIYA - Tool Calling Handler
# ==============================================================================
# This file handles the execution of tools called by the model.
# It supports:
# 1. Parsing tool calls generated by the LLM
# 2. Executing the tool via tools_registry
# 3. Formatting tool results back into standard OpenAI message format
# ==============================================================================

import json
from typing import Any, Dict
from backend.registries.tools_registry import execute_tool


def handle_single_tool_call(tool_call: Any) -> Dict[str, Any]:
    """
    Takes a single tool_call object from the model, executes the tool,
    and returns a formatted dictionary containing the result and tool message.
    """
    # 1. Extract tool call ID
    tool_call_id = getattr(tool_call, "id", None) or "call_default"

    # 2. Extract function name and arguments
    function_data = getattr(tool_call, "function", None)
    if function_data:
        tool_name = getattr(function_data, "name", "")
        arguments_raw = getattr(function_data, "arguments", "{}")
    elif isinstance(tool_call, dict):
        tool_call_id = tool_call.get("id", "call_default")
        fn = tool_call.get("function", {})
        tool_name = fn.get("name", "")
        arguments_raw = fn.get("arguments", "{}")
    else:
        tool_name = ""
        arguments_raw = "{}"

    # 3. Parse JSON arguments if they are a string
    if isinstance(arguments_raw, str):
        try:
            arguments = json.loads(arguments_raw)
        except Exception:
            arguments = {"command": arguments_raw}
    else:
        arguments = arguments_raw

    # 4. Execute the tool using the central tools registry
    output_result = execute_tool(tool_name, arguments)

    # 5. Format the message for OpenAI so the model can read the result in the next step
    tool_message = {
        "role": "tool",
        "tool_call_id": tool_call_id,
        "name": tool_name,
        "content": str(output_result)
    }

    return {
        "tool_name": tool_name,
        "arguments": arguments,
        "result": output_result,
        "tool_message": tool_message
    }
