# ==============================================================================
# KRIYA - Sovereign LLM Client & Request Schemas
# ==============================================================================
# Manages connections and completions to the Sovereign LLM Load Balancer / Phone Gateway.
# Supports both standard chat tokens and reasoning / thinking stream tokens (DeepSeek-R1, Qwen).
# ==============================================================================

import os
from pathlib import Path
from typing import Any, AsyncGenerator, Dict, Generator, List, Optional, Union
from dotenv import load_dotenv
from openai import AsyncOpenAI, OpenAI
from pydantic import BaseModel, Field

# Load environment variables from .env in the project root directory
env_path = Path(__file__).resolve().parent.parent.parent / ".env"
load_dotenv(dotenv_path=env_path)

# Central Sovereign Load Balancer configuration (loaded strictly from .env)
DEFAULT_BASE_URL = os.getenv("MODEL_BALANCER_URL", "http://100.127.46.50:8000/v1")
DEFAULT_API_KEY = os.getenv("MODEL_BALANCER_API_KEY") or os.getenv("MODEL_BALANCER_KEY") or "sih2026"


class ChatMessage(BaseModel):
    """Represents an individual message in a chat history."""
    role: str = Field(..., description="Role of the sender: system, user, assistant, or tool")
    content: Optional[str] = Field(None, description="Text content of the message")
    name: Optional[str] = Field(None, description="Optional name of the tool or agent")
    tool_call_id: Optional[str] = Field(None, description="Tool call reference ID if role is tool")
    tool_calls: Optional[List[Dict[str, Any]]] = Field(None, description="Tool calls generated by assistant")


class FunctionDefinition(BaseModel):
    """Defines a callable function schema for tool calling."""
    name: str = Field(..., description="Name of the function")
    description: Optional[str] = Field(None, description="Description of what the function does")
    parameters: Optional[Dict[str, Any]] = Field(None, description="JSON schema of function parameters")


class ToolDefinition(BaseModel):
    """OpenAI-compatible tool definition wrapper."""
    type: str = Field(default="function", description="Tool type, typically 'function'")
    function: FunctionDefinition = Field(..., description="Function specification")


class ModelRequest(BaseModel):
    """
    Complete business logic schema for sending generation requests
    to the Sovereign Load Balancer.
    """
    user_content: str = Field(..., description="The prompt or query from the user")
    system_content: Optional[str] = Field(None, description="System instruction or persona for the model")
    history_messages: Optional[List[ChatMessage]] = Field(default=None, description="Prior conversation history messages")
    model: Optional[str] = Field(default="default", description="Target model or routing tag")
    temperature: Optional[float] = Field(default=0.2, description="Sampling temperature")
    top_p: Optional[float] = Field(default=0.95, description="Nucleus sampling threshold")
    max_tokens: Optional[int] = Field(default=None, description="Maximum number of tokens to generate")
    stream: Optional[bool] = Field(default=False, description="Whether to stream back partial tokens")
    tools: Optional[List[ToolDefinition]] = Field(default=None, description="List of available tools/functions")
    tool_choice: Optional[Union[str, Dict[str, Any]]] = Field(default=None, description="Tool choice mode")
    stop: Optional[Union[str, List[str]]] = Field(default=None, description="Sequences where model will stop generating")
    presence_penalty: Optional[float] = Field(default=None, description="Presence penalty")
    frequency_penalty: Optional[float] = Field(default=None, description="Frequency penalty")
    thinking: Optional[bool] = Field(default=None, description="Toggle reasoning/thinking mode")

    def to_messages_list(self) -> List[Dict[str, Any]]:
        """Converts system_content, history_messages, and user_content into standard message array."""
        messages: List[Dict[str, Any]] = []
        if self.system_content:
            messages.append({"role": "system", "content": self.system_content})
        if self.history_messages:
            for msg in self.history_messages:
                messages.append(msg.model_dump(exclude_none=True))
        messages.append({"role": "user", "content": self.user_content})
        return messages

    def to_openai_payload(self) -> Dict[str, Any]:
        """Converts the request into kwargs dictionary ready for client.chat.completions.create."""
        payload: Dict[str, Any] = {
            "model": self.model or "default",
            "messages": self.to_messages_list(),
            "temperature": self.temperature if self.temperature is not None else 0.2,
            "stream": bool(self.stream),
        }

        if self.top_p is not None:
            payload["top_p"] = self.top_p
        if self.max_tokens is not None:
            payload["max_tokens"] = self.max_tokens
        if self.stop is not None:
            payload["stop"] = self.stop
        if self.presence_penalty is not None:
            payload["presence_penalty"] = self.presence_penalty
        if self.frequency_penalty is not None:
            payload["frequency_penalty"] = self.frequency_penalty

        if self.tools:
            payload["tools"] = [t.model_dump(exclude_none=True) for t in self.tools]
            if self.tool_choice:
                payload["tool_choice"] = self.tool_choice

        if self.thinking is not None:
            extra_body = payload.get("extra_body", {})
            extra_body["enable_thinking"] = self.thinking
            extra_body["chat_template_kwargs"] = {"enable_thinking": self.thinking}
            payload["extra_body"] = extra_body

        return payload


def get_openai_client(
    base_url: Optional[str] = None,
    api_key: Optional[str] = None
) -> OpenAI:
    """Returns a synchronous OpenAI client configured for the local model balancer."""
    return OpenAI(
        base_url=base_url or DEFAULT_BASE_URL,
        api_key=api_key or DEFAULT_API_KEY
    )


def get_async_openai_client(
    base_url: Optional[str] = None,
    api_key: Optional[str] = None
) -> AsyncOpenAI:
    """Returns an asynchronous OpenAI client configured for the local model balancer."""
    return AsyncOpenAI(
        base_url=base_url or DEFAULT_BASE_URL,
        api_key=api_key or DEFAULT_API_KEY
    )


def send_chat_request(
    request: ModelRequest,
    base_url: Optional[str] = None,
    api_key: Optional[str] = None
) -> Any:
    """Sends a synchronous chat completion request to the model load balancer."""
    client = get_openai_client(base_url, api_key)
    payload = request.to_openai_payload()
    payload["stream"] = False
    return client.chat.completions.create(**payload)


async def send_async_chat_request(
    request: ModelRequest,
    base_url: Optional[str] = None,
    api_key: Optional[str] = None
) -> Any:
    """Sends an asynchronous chat completion request to the model load balancer."""
    client = get_async_openai_client(base_url, api_key)
    payload = request.to_openai_payload()
    payload["stream"] = False
    return await client.chat.completions.create(**payload)


def stream_chat_request(
    request: ModelRequest,
    base_url: Optional[str] = None,
    api_key: Optional[str] = None
) -> Generator[str, None, None]:
    """Streams tokens synchronously from the model load balancer as they are generated."""
    client = get_openai_client(base_url, api_key)
    payload = request.to_openai_payload()
    payload["stream"] = True

    response_stream = client.chat.completions.create(**payload)
    for chunk in response_stream:
        if chunk.choices:
            delta = chunk.choices[0].delta
            text = delta.content or getattr(delta, "reasoning_content", None)
            if text:
                yield text


async def stream_async_chat_request(
    request: ModelRequest,
    base_url: Optional[str] = None,
    api_key: Optional[str] = None
) -> AsyncGenerator[str, None]:
    """Streams tokens asynchronously from the model load balancer as they are generated."""
    client = get_async_openai_client(base_url, api_key)
    payload = request.to_openai_payload()
    payload["stream"] = True

    response_stream = await client.chat.completions.create(**payload)
    async for chunk in response_stream:
        if chunk.choices:
            delta = chunk.choices[0].delta
            text = delta.content or getattr(delta, "reasoning_content", None)
            if text:
                yield text
